version: "3"
services:
  api-server:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run prodsitesje
    volumes: 
      - .:/tmp
      - .:/app/backend
      - library_backend:/app/backend/node_modules
      - /reactcert/:/app/backend/reactcert
    ports:
      - "3000:3000"
    restart: always
  api-server-https:
    container_name: apihttps
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run prodsitesjes
    volumes: 
      - .:/tmp
      - .:/app/backend
      - libraryhttps_backend:/app/backend/node_modules
      - /reactcert/:/app/backend/reactcert
      - /apps/uploads:/app/backend/uploads
    ports:
      - "4100:3000"
    restart: always
volumes:
  library_backend:
    driver: local
  libraryhttps_backend:
    driver: local